### ISSUE TITLE
How to create images?

### ISSUE THREAD

**Issue by adammaj1** [etiennebresciani/flowtopolopy#1]
Hi

Thx for the prograM
I can run : 
`
 python3 dipole_2D.py
dist = 5.546860852962499
threshold = 0.00012307066128851147
dist = 14.142135623730951
0 1654
1 1476
2 452
3 497
4 488
`

It works with no errors. But how can I make images ?

**Comment by bujack** [comment]
You can simply drag and drop the produced files into ParaView

Mit freundlichen Grüßen
Roxana Bujack

**Comment by adammaj1** [comment]
I have to look into dir dipole_2D_files !

I got it
